# SPDX-License-Identifier: GPL-2.0
# Makefile for the att security module

obj-$(CONFIG_SECURITY_ATT) := att.o tpm_extend_example.o att_queue.o att_tree.o att_tpm_event_list.o 
obj-$(CONFIG_SECURITY_ATT) += data_structs/generic_list.o
obj-$(CONFIG_ATT_KUNIT_TEST) += kunit/